export const CATALOG_OBJECT_TYPES = [
  {
    id: 'rug-round',
    label: 'Circular Rug',
    size: { width: 2438, depth: 2438 },
    surfaces: ['fabric', 'grey', 'blue', 'green', 'linen', 'rust', 'dots', 'stripes', 'check'],
    stands: 'free',
    layer: 'under',
    symbol: 'rug-round.svg',
    rooms: ['living_room', 'bedroom', 'dining_room', 'any'],
  },
  {
    id: 'rug-rect',
    label: 'Rectangular Rug',
    size: { width: 2438, depth: 1829 },
    surfaces: ['fabric', 'grey', 'blue', 'green', 'linen', 'rust', 'dots', 'stripes', 'check'],
    stands: 'free',
    layer: 'under',
    symbol: 'rug-rect.svg',
    rooms: ['living_room', 'bedroom', 'dining_room', 'any'],
  },
  {
    id: 'picture-frame',
    label: 'Picture Frame',
    size: { width: 330, depth: 51 },
    surfaces: ['white', 'grey', 'black'],
    stands: 'wall',
    symbol: 'picture-frame.svg',
    rooms: ['living_room', 'bedroom', 'any'],
  },
  {
    id: 'floor-lamp',
    label: 'Floor Lamp',
    size: { width: 533, depth: 533 },
    surfaces: ['white', 'grey', 'black'],
    stands: 'free',
    layer: 'over',
    symbol: 'floor-lamp.svg',
    rooms: ['living_room', 'bedroom', 'office', 'any'],
  },
  {
    id: 'table-lamp',
    label: 'Table Lamp',
    size: { width: 356, depth: 356 },
    surfaces: ['white', 'grey', 'black'],
    stands: 'free',
    layer: 'over',
    symbol: 'table-lamp.svg',
    rooms: ['living_room', 'bedroom', 'office', 'any'],
  },
  {
    id: 'potted-plant',
    label: 'Large Plant',
    size: { width: 1067, depth: 1067 },
    surfaces: ['green'],
    stands: 'free',
    symbol: 'potted-plant.svg',
    rooms: ['living_room', 'bedroom', 'office', 'any'],
  },
  {
    id: 'potted-plant-m',
    label: 'Medium Plant',
    size: { width: 838, depth: 838 },
    surfaces: ['green'],
    stands: 'free',
    symbol: 'potted-plant-m.svg',
    rooms: ['living_room', 'bedroom', 'office', 'any'],
  },
  {
    id: 'potted-plant-s',
    label: 'Small Plant',
    size: { width: 660, depth: 660 },
    surfaces: ['green'],
    stands: 'free',
    layer: 'over',
    symbol: 'potted-plant-s.svg',
    rooms: ['living_room', 'bedroom', 'office', 'any'],
  },
  {
    id: 'cal-king-bed',
    label: 'Cal-King Bed',
    size: { width: 1854, depth: 2159 },
    surfaces: ['white', 'linen', 'grey', 'blue', 'green', 'fabric', 'rust'],
    stands: 'wall',
    symbol: 'cal-king-bed.svg',
    rooms: ['bedroom'],
  },
  {
    id: 'king-bed',
    label: 'King Bed',
    size: { width: 1956, depth: 2057 },
    surfaces: ['white', 'linen', 'grey', 'blue', 'green', 'fabric', 'rust'],
    stands: 'wall',
    symbol: 'king-bed.svg',
    rooms: ['bedroom'],
  },
  {
    id: 'queen-bed',
    label: 'Queen Bed',
    size: { width: 1549, depth: 2057 },
    surfaces: ['white', 'linen', 'grey', 'blue', 'green', 'fabric', 'rust'],
    stands: 'wall',
    symbol: 'queen-bed.svg',
    rooms: ['bedroom'],
  },
  {
    id: 'full-bed',
    label: 'Full Bed',
    size: { width: 1397, depth: 1930 },
    surfaces: ['white', 'linen', 'grey', 'blue', 'green', 'fabric', 'rust'],
    stands: 'wall',
    symbol: 'full-bed.svg',
    rooms: ['bedroom'],
  },
  {
    id: 'twin-bed',
    label: 'Twin Bed',
    size: { width: 991, depth: 1930 },
    surfaces: ['white', 'linen', 'grey', 'blue', 'green', 'fabric', 'rust'],
    stands: 'wall',
    symbol: 'twin-bed.svg',
    rooms: ['bedroom'],
  },
  {
    id: 'crib',
    label: 'Crib',
    size: { width: 711, depth: 1346 },
    surfaces: ['white', 'linen', 'grey', 'blue', 'green', 'fabric', 'rust'],
    stands: 'wall',
    symbol: 'crib.svg',
    rooms: ['bedroom'],
  },
  {
    id: 'nightstand',
    label: 'Nightstand',
    size: { width: 635, depth: 533 },
    surfaces: ['walnut', 'oak', 'white', 'black', 'marble', 'steel'],
    stands: 'wall',
    symbol: 'nightstand.svg',
    rooms: ['bedroom'],
  },
  {
    id: 'dresser',
    label: 'Dresser',
    size: { width: 1295, depth: 787 },
    surfaces: ['walnut', 'oak', 'white', 'black', 'marble', 'steel'],
    stands: 'wall',
    symbol: 'dresser.svg',
    rooms: ['bedroom'],
  },
  {
    id: 'toilet-tank',
    label: 'Toilet',
    size: { width: 483, depth: 737 },
    surfaces: ['white', 'black'],
    stands: 'wall',
    symbol: 'toilet-tank.svg',
    rooms: ['full_bathroom', 'half_bathroom'],
  },
  {
    id: 'vanity-sink',
    label: 'Single-Sink Vanity',
    size: { width: 813, depth: 635 },
    surfaces: ['white', 'black'],
    stands: 'wall',
    symbol: 'vanity-sink.svg',
    rooms: ['full_bathroom', 'half_bathroom'],
  },
  {
    id: 'vanity-double',
    label: 'Double-Sink Vanity',
    size: { width: 1575, depth: 635 },
    surfaces: ['white', 'black'],
    stands: 'wall',
    symbol: 'vanity-double.svg',
    rooms: ['full_bathroom'],
  },
  {
    id: 'bathtub',
    label: 'Built-in Bathtub',
    size: { width: 1549, depth: 838 },
    surfaces: ['white', 'black'],
    stands: 'wall',
    symbol: 'bathtub.svg',
    rooms: ['full_bathroom'],
  },
  {
    id: 'bathtub-free',
    label: 'Free-Standing Bathtub',
    size: { width: 1549, depth: 914 },
    surfaces: ['white', 'black'],
    stands: 'free',
    symbol: 'bathtub-free.svg',
    rooms: ['full_bathroom'],
  },
  {
    id: 'shower-s',
    label: 'Small Shower',
    size: { width: 838, depth: 838 },
    surfaces: ['white', 'black'],
    stands: 'wall',
    symbol: 'shower-s.svg',
    rooms: ['full_bathroom'],
  },
  {
    id: 'shower-m',
    label: 'Medium Shower',
    size: { width: 1143, depth: 1143 },
    surfaces: ['white', 'black'],
    stands: 'wall',
    symbol: 'shower-m.svg',
    rooms: ['full_bathroom'],
  },
  {
    id: 'shower-l',
    label: 'Large Shower',
    size: { width: 1549, depth: 940 },
    surfaces: ['white', 'black'],
    stands: 'wall',
    symbol: 'shower-l.svg',
    rooms: ['full_bathroom'],
  },
  {
    id: 'chair-ottoman',
    label: 'Lounge Chair with Ottoman',
    size: { width: 838, depth: 1448 },
    surfaces: ['fabric', 'grey', 'blue', 'green', 'linen', 'rust', 'white'],
    stands: 'free',
    symbol: 'chair-ottoman.svg',
    rooms: ['living_room', 'bedroom'],
  },
  {
    id: 'club-chair',
    label: 'Armchair',
    size: { width: 940, depth: 838 },
    surfaces: ['fabric', 'grey', 'blue', 'green', 'linen', 'rust', 'white'],
    stands: 'free',
    symbol: 'club-chair.svg',
    rooms: ['living_room', 'bedroom', 'office'],
  },
  {
    id: 'sofa-2',
    label: '2-Seat Sofa',
    size: { width: 1702, depth: 940 },
    surfaces: ['fabric', 'grey', 'blue', 'green', 'linen', 'rust', 'white'],
    stands: 'wall',
    symbol: 'sofa-2.svg',
    rooms: ['living_room'],
  },
  {
    id: 'sofa-3',
    label: '3-Seat Sofa',
    size: { width: 2388, depth: 965 },
    surfaces: ['fabric', 'grey', 'blue', 'green', 'linen', 'rust', 'white'],
    stands: 'wall',
    symbol: 'sofa-3.svg',
    rooms: ['living_room'],
  },
  {
    id: 'sofa-l',
    label: 'Sectional Sofa',
    size: { width: 3023, depth: 1829 },
    surfaces: ['fabric', 'grey', 'blue', 'green', 'linen', 'rust', 'white'],
    stands: 'wall',
    symbol: 'sofa-l.svg',
    rooms: ['living_room'],
  },
  {
    id: 'coffee-table',
    label: 'Coffee Table',
    size: { width: 914, depth: 914 },
    surfaces: ['oak', 'walnut', 'marble', 'glass', 'white', 'black', 'steel'],
    stands: 'free',
    symbol: 'coffee-table.svg',
    rooms: ['living_room'],
  },
  {
    id: 'media-unit',
    label: 'Media Unit with TV',
    size: { width: 1626, depth: 356 },
    surfaces: ['walnut', 'oak', 'white', 'black', 'marble', 'steel'],
    stands: 'wall',
    symbol: 'media-unit.svg',
    rooms: ['living_room'],
  },
  {
    id: 'side-table',
    label: 'Side Table',
    size: { width: 584, depth: 584 },
    surfaces: ['oak', 'walnut', 'marble', 'glass', 'white', 'black', 'steel'],
    stands: 'free',
    symbol: 'side-table.svg',
    rooms: ['living_room', 'bedroom', 'any'],
  },
  {
    id: 'bookshelf',
    label: 'Bookshelf',
    size: { width: 940, depth: 330 },
    surfaces: ['walnut', 'oak', 'white', 'black', 'marble', 'steel'],
    stands: 'wall',
    symbol: 'bookshelf.svg',
    rooms: ['living_room', 'office', 'bedroom', 'any'],
  },
  {
    id: 'credenza',
    label: 'Credenza',
    size: { width: 1549, depth: 559 },
    surfaces: ['walnut', 'oak', 'white', 'black', 'marble', 'steel'],
    stands: 'wall',
    symbol: 'credenza.svg',
    rooms: ['living_room', 'bedroom', 'any'],
  },
  {
    id: 'lounge-chair',
    label: 'Large Lounge Chair',
    size: { width: 660, depth: 1753 },
    surfaces: ['fabric', 'grey', 'blue', 'green', 'linen', 'rust', 'white'],
    stands: 'free',
    symbol: 'lounge-chair.svg',
    rooms: ['any'],
  },
  {
    id: 'lounge-chair-s',
    label: 'Small Lounge Chair',
    size: { width: 660, depth: 787 },
    surfaces: ['fabric', 'grey', 'blue', 'green', 'linen', 'rust', 'white'],
    stands: 'free',
    symbol: 'lounge-chair-s.svg',
    rooms: ['any'],
  },
  {
    id: 'bbq',
    label: 'BBQ Grill',
    size: { width: 1575, depth: 762 },
    surfaces: ['white', 'grey', 'black'],
    stands: 'wall',
    symbol: 'bbq.svg',
    rooms: ['any'],
  },
  {
    id: 'outdoor-dining',
    label: 'Outdoor Dining Set',
    size: { width: 2769, depth: 2769 },
    surfaces: ['oak', 'walnut', 'marble', 'glass', 'white', 'black', 'steel'],
    stands: 'free',
    symbol: 'outdoor-dining.svg',
    rooms: ['any'],
  },
  {
    id: 'office-chair',
    label: 'Office Chair',
    size: { width: 711, depth: 660 },
    surfaces: ['fabric', 'grey', 'blue', 'green', 'linen', 'rust', 'white'],
    stands: 'free',
    symbol: 'office-chair.svg',
    rooms: ['office'],
  },
  {
    id: 'office-desk',
    label: 'Free-Standing Office Desk',
    size: { width: 1829, depth: 813 },
    surfaces: ['oak', 'walnut', 'marble', 'glass', 'white', 'black', 'steel'],
    stands: 'wall',
    symbol: 'office-desk.svg',
    rooms: ['office', 'bedroom', 'any'],
  },
  {
    id: 'office-desk-l',
    label: 'Corner Office Desk',
    size: { width: 2057, depth: 2057 },
    surfaces: ['oak', 'walnut', 'marble', 'glass', 'white', 'black', 'steel'],
    stands: 'wall',
    symbol: 'office-desk-l.svg',
    rooms: ['office', 'any'],
  },
  {
    id: 'filing-cabinet',
    label: 'Filing Cabinet',
    size: { width: 457, depth: 533 },
    surfaces: ['walnut', 'oak', 'white', 'black', 'marble', 'steel'],
    stands: 'wall',
    symbol: 'filing-cabinet.svg',
    rooms: ['office', 'any'],
  },
  {
    id: 'console-mirror',
    label: 'Console with Mirror',
    size: { width: 1143, depth: 483 },
    surfaces: ['walnut', 'oak', 'white', 'black', 'marble', 'steel'],
    stands: 'wall',
    symbol: 'console-mirror.svg',
    rooms: ['entry', 'any'],
  },
  {
    id: 'bench',
    label: 'Bench',
    size: { width: 2032, depth: 406 },
    surfaces: ['fabric', 'grey', 'blue', 'green', 'linen', 'rust', 'white'],
    stands: 'wall',
    symbol: 'bench.svg',
    rooms: ['living_room', 'bedroom', 'entry', 'any'],
  },
  {
    id: 'coat-stand',
    label: 'Coat Stand',
    size: { width: 432, depth: 432 },
    surfaces: ['white', 'grey', 'black'],
    stands: 'wall',
    symbol: 'coat-stand.svg',
    rooms: ['entry', 'any'],
  },
  {
    id: 'washer-dryer-stacked',
    label: 'Stacked Washer & Dryer',
    size: { width: 737, depth: 889 },
    surfaces: ['steel', 'white', 'graphite', 'black'],
    stands: 'wall',
    abuts: true,
    symbol: 'washer-dryer-stacked.svg',
    rooms: ['any'],
  },
  {
    id: 'washer-dryer',
    label: 'Side-by-Side Washer & Dryer',
    size: { width: 1549, depth: 889 },
    surfaces: ['steel', 'white', 'graphite', 'black'],
    stands: 'wall',
    abuts: true,
    symbol: 'washer-dryer.svg',
    rooms: ['any'],
  },
  {
    id: 'dining-round-4',
    label: 'Round Dining Set (4 Chairs)',
    size: { width: 1600, depth: 1600 },
    surfaces: ['oak', 'walnut', 'marble', 'glass', 'white', 'black', 'steel'],
    stands: 'free',
    symbol: 'dining-round-4.svg',
    rooms: ['dining_room'],
  },
  {
    id: 'dining-square-4',
    label: 'Square Dining Set (4 Chairs)',
    size: { width: 1600, depth: 1600 },
    surfaces: ['oak', 'walnut', 'marble', 'glass', 'white', 'black', 'steel'],
    stands: 'free',
    symbol: 'dining-square-4.svg',
    rooms: ['dining_room'],
  },
  {
    id: 'dining-6',
    label: 'Rectangular Dining Set (6 Chairs)',
    size: { width: 1600, depth: 2210 },
    surfaces: ['oak', 'walnut', 'marble', 'glass', 'white', 'black', 'steel'],
    stands: 'free',
    symbol: 'dining-6.svg',
    rooms: ['dining_room'],
  },
  {
    id: 'dining-square-8',
    label: 'Square Dining Set (8 Chairs)',
    size: { width: 2489, depth: 2362 },
    surfaces: ['oak', 'walnut', 'marble', 'glass', 'white', 'black', 'steel'],
    stands: 'free',
    symbol: 'dining-square-8.svg',
    rooms: ['dining_room'],
  },
  {
    id: 'dining-8',
    label: 'Rectangular Dining Set (8 Chairs)',
    size: { width: 1600, depth: 2362 },
    surfaces: ['oak', 'walnut', 'marble', 'glass', 'white', 'black', 'steel'],
    stands: 'free',
    symbol: 'dining-8.svg',
    rooms: ['dining_room'],
  },
  {
    id: 'kitchen-i-mini',
    label: 'Compact Straight Cabinet Set',
    size: { width: 2845, depth: 762 },
    surfaces: ['white', 'grey', 'black'],
    stands: 'wall',
    symbol: 'kitchen-i-mini.svg',
    rooms: ['kitchen'],
  },
  {
    id: 'kitchen-l-mini',
    label: 'Compact L-Shaped Cabinet Set',
    size: { width: 2388, depth: 2032 },
    surfaces: ['white', 'grey', 'black'],
    stands: 'wall',
    symbol: 'kitchen-l-mini.svg',
    rooms: ['kitchen'],
  },
  {
    id: 'kitchen-i',
    label: 'Straight Cabinet Set',
    size: { width: 3797, depth: 737 },
    surfaces: ['walnut', 'oak', 'white', 'black', 'marble', 'steel'],
    stands: 'wall',
    symbol: 'kitchen-i.svg',
    rooms: ['kitchen'],
  },
  {
    id: 'kitchen-l',
    label: 'L-Shaped Cabinet Set',
    size: { width: 3251, depth: 2565 },
    surfaces: ['walnut', 'oak', 'white', 'black', 'marble', 'steel'],
    stands: 'wall',
    symbol: 'kitchen-l.svg',
    rooms: ['kitchen'],
  },
  {
    id: 'kitchen-u',
    label: 'U-Shaped Cabinet Set',
    size: { width: 3226, depth: 3023 },
    surfaces: ['walnut', 'oak', 'white', 'black', 'marble', 'steel'],
    stands: 'wall',
    symbol: 'kitchen-u.svg',
    rooms: ['kitchen'],
  },
  {
    id: 'kitchen-u-wall',
    label: 'U-Shaped Set with Wall Cabinets',
    size: { width: 3226, depth: 3023 },
    surfaces: ['walnut', 'oak', 'white', 'black', 'marble', 'steel'],
    stands: 'wall',
    symbol: 'kitchen-u-wall.svg',
    rooms: ['kitchen'],
  },
  {
    id: 'kitchen-l-mini-wall',
    label: 'Compact L-Shaped Set with Wall Cabinets',
    size: { width: 2388, depth: 2032 },
    surfaces: ['white', 'grey', 'black'],
    stands: 'wall',
    symbol: 'kitchen-l-mini-wall.svg',
    rooms: ['kitchen'],
  },
  {
    id: 'kitchen-i-wall',
    label: 'Straight Set with Wall Cabinets',
    size: { width: 3797, depth: 737 },
    surfaces: ['walnut', 'oak', 'white', 'black', 'marble', 'steel'],
    stands: 'wall',
    symbol: 'kitchen-i-wall.svg',
    rooms: ['kitchen'],
  },
  {
    id: 'kitchen-i-mini-wall',
    label: 'Compact Straight Set with Wall Cabinets',
    size: { width: 2845, depth: 762 },
    surfaces: ['white', 'grey', 'black'],
    stands: 'wall',
    symbol: 'kitchen-i-mini-wall.svg',
    rooms: ['kitchen'],
  },
  {
    id: 'island-2',
    label: 'Kitchen Island (2 Stools)',
    size: { width: 1422, depth: 1397 },
    surfaces: ['walnut', 'oak', 'white', 'black', 'marble', 'steel'],
    stands: 'free',
    symbol: 'island-2.svg',
    rooms: ['kitchen'],
  },
  {
    id: 'island-4',
    label: 'Kitchen Island (4 Stools)',
    size: { width: 2794, depth: 1397 },
    surfaces: ['walnut', 'oak', 'white', 'black', 'marble', 'steel'],
    stands: 'free',
    symbol: 'island-4.svg',
    rooms: ['kitchen'],
  },
  {
    id: 'island-2-sink',
    label: 'Kitchen Island with Sink (2 Stools)',
    size: { width: 1422, depth: 1397 },
    surfaces: ['white', 'black'],
    stands: 'free',
    symbol: 'island-2-sink.svg',
    rooms: ['kitchen'],
  },
  {
    id: 'island-4-sink',
    label: 'Kitchen Island with Sink (4 Stools)',
    size: { width: 2794, depth: 1397 },
    surfaces: ['white', 'black'],
    stands: 'free',
    symbol: 'island-4-sink.svg',
    rooms: ['kitchen'],
  },
  {
    id: 'counter-straight',
    label: 'Straight Kitchen Counter',
    size: { width: 1245, depth: 711 },
    surfaces: ['walnut', 'oak', 'white', 'black', 'marble', 'steel'],
    stands: 'wall',
    abuts: true,
    symbol: 'counter-straight.svg',
    rooms: ['kitchen'],
  },
  {
    id: 'counter-l',
    label: 'L-Shaped Kitchen Counter',
    size: { width: 2515, depth: 1245 },
    surfaces: ['walnut', 'oak', 'white', 'black', 'marble', 'steel'],
    stands: 'wall',
    abuts: true,
    symbol: 'counter-l.svg',
    rooms: ['kitchen'],
  },
  {
    id: 'kitchen-sink',
    label: 'Kitchen Sink',
    size: { width: 2489, depth: 737 },
    surfaces: ['white', 'black'],
    stands: 'wall',
    abuts: true,
    symbol: 'kitchen-sink.svg',
    rooms: ['kitchen'],
  },
  {
    id: 'stove',
    label: 'Stove',
    size: { width: 762, depth: 737 },
    surfaces: ['steel', 'white', 'graphite', 'black'],
    stands: 'wall',
    abuts: true,
    symbol: 'stove.svg',
    rooms: ['kitchen'],
  },
  {
    id: 'refrigerator',
    label: 'Refrigerator',
    size: { width: 711, depth: 686 },
    surfaces: ['steel', 'white', 'graphite', 'black'],
    stands: 'wall',
    abuts: true,
    symbol: 'refrigerator.svg',
    rooms: ['kitchen'],
  },
  {
    id: 'dishwasher',
    label: 'Dishwasher',
    size: { width: 635, depth: 660 },
    surfaces: ['steel', 'white', 'graphite', 'black'],
    stands: 'wall',
    abuts: true,
    symbol: 'dishwasher.svg',
    rooms: ['kitchen'],
  },
  {
    id: 'water-heater',
    label: 'Water Heater',
    size: { width: 635, depth: 635 },
    surfaces: ['steel', 'white', 'graphite', 'black'],
    stands: 'wall',
    symbol: 'water-heater.svg',
    rooms: ['any'],
  },
  {
    id: 'hvac',
    label: 'HVAC Unit',
    size: { width: 1016, depth: 610 },
    surfaces: ['steel', 'white', 'graphite', 'black'],
    stands: 'wall',
    symbol: 'hvac.svg',
    rooms: ['any'],
  },
  {
    id: 'clothing-rack',
    label: 'Clothing Rack',
    size: { width: 1321, depth: 508 },
    surfaces: ['white', 'grey', 'black'],
    stands: 'wall',
    symbol: 'clothing-rack.svg',
    rooms: ['full_bathroom', 'bedroom', 'any'],
  },
  {
    id: 'built-in-shelf',
    label: 'Built-in Shelf',
    size: { width: 940, depth: 381 },
    surfaces: ['walnut', 'oak', 'white', 'black', 'marble', 'steel'],
    stands: 'wall',
    symbol: 'built-in-shelf.svg',
    rooms: ['pantry', 'walk_in', 'any'],
  },
  {
    id: 'sedan',
    label: 'Sedan',
    size: { width: 2007, depth: 4877 },
    surfaces: ['white', 'black', 'grey', 'steel', 'blue'],
    stands: 'free',
    symbol: 'sedan.svg',
    rooms: ['any'],
  },
  {
    id: 'suv',
    label: 'SUV',
    size: { width: 2057, depth: 4699 },
    surfaces: ['white', 'black', 'grey', 'steel', 'blue'],
    stands: 'free',
    symbol: 'suv.svg',
    rooms: ['any'],
  },
  {
    id: 'stairs-straight',
    label: 'Straight Staircase',
    size: { width: 940, depth: 3734 },
    surfaces: ['walnut', 'oak', 'white', 'black', 'marble', 'steel'],
    stands: 'wall',
    symbol: 'stairs-straight.svg',
    rooms: ['any'],
  },
  {
    id: 'stairs-u',
    label: 'U-Shaped Staircase',
    size: { width: 1956, depth: 2718 },
    surfaces: ['walnut', 'oak', 'white', 'black', 'marble', 'steel'],
    stands: 'wall',
    symbol: 'stairs-u.svg',
    rooms: ['any'],
  },
  {
    id: 'stairs-l-landing',
    label: 'L-Shaped Staircase (Landing)',
    size: { width: 3480, depth: 1448 },
    surfaces: ['walnut', 'oak', 'white', 'black', 'marble', 'steel'],
    stands: 'wall',
    symbol: 'stairs-l-landing.svg',
    rooms: ['any'],
  },
  {
    id: 'stairs-l-winder',
    label: 'L-Shaped Staircase (Winder)',
    size: { width: 3226, depth: 1194 },
    surfaces: ['walnut', 'oak', 'white', 'black', 'marble', 'steel'],
    stands: 'wall',
    symbol: 'stairs-l-winder.svg',
    rooms: ['any'],
  },
  {
    id: 'column',
    label: 'Column',
    size: { width: 305, depth: 305 },
    surfaces: ['white', 'grey', 'black'],
    stands: 'free',
    symbol: 'column.svg',
    rooms: ['any'],
  },
  {
    id: 'post',
    label: 'Post',
    size: { width: 229, depth: 229 },
    surfaces: ['white', 'grey', 'black'],
    stands: 'free',
    symbol: 'post.svg',
    rooms: ['any'],
  },
  {
    id: 'railing',
    label: 'Railing',
    size: { width: 2311, depth: 127 },
    surfaces: ['white', 'grey', 'black'],
    stands: 'wall',
    symbol: 'railing.svg',
    rooms: ['any'],
  },
  {
    id: 'box',
    label: 'Generic Object',
    size: { width: 635, depth: 432 },
    surfaces: ['white', 'grey', 'black'],
    stands: 'free',
    symbol: 'box.svg',
    rooms: ['any'],
  },
  {
    id: 'pool-table',
    label: 'Pool Table',
    size: { width: 1626, depth: 2896 },
    surfaces: ['white', 'grey', 'black'],
    stands: 'free',
    symbol: 'pool-table.svg',
    rooms: ['recreation_room', 'game_room'],
  },
  {
    id: 'ping-pong',
    label: 'Ping Pong Table',
    size: { width: 1829, depth: 2743 },
    surfaces: ['white', 'grey', 'black'],
    stands: 'free',
    symbol: 'ping-pong.svg',
    rooms: ['recreation_room', 'game_room'],
  },
  {
    id: 'bar',
    label: 'Built-in Bar',
    size: { width: 2057, depth: 635 },
    surfaces: ['walnut', 'oak', 'white', 'black', 'marble', 'steel'],
    stands: 'wall',
    symbol: 'bar.svg',
    rooms: ['recreation_room', 'game_room', 'family_room', 'any'],
  },
  {
    id: 'bar-island',
    label: 'Built-in Bar w/ Serving Island',
    size: { width: 2057, depth: 2565 },
    surfaces: ['walnut', 'oak', 'white', 'black', 'marble', 'steel'],
    stands: 'wall',
    symbol: 'bar-island.svg',
    rooms: ['recreation_room', 'game_room', 'family_room', 'any'],
  },
  {
    id: 'treadmill',
    label: 'Treadmill',
    size: { width: 889, depth: 2032 },
    surfaces: ['white', 'grey', 'black'],
    stands: 'wall',
    symbol: 'treadmill.svg',
    rooms: ['home_gym'],
  },
  {
    id: 'exercise-bike',
    label: 'Exercise Bike',
    size: { width: 610, depth: 1321 },
    surfaces: ['white', 'grey', 'black'],
    stands: 'free',
    symbol: 'exercise-bike.svg',
    rooms: ['home_gym'],
  },
  {
    id: 'weight-rack',
    label: 'Weight Rack',
    size: { width: 1194, depth: 457 },
    surfaces: ['white', 'grey', 'black'],
    stands: 'wall',
    symbol: 'weight-rack.svg',
    rooms: ['home_gym'],
  },
  {
    id: 'gym-bench',
    label: 'Gym Bench',
    size: { width: 457, depth: 1372 },
    surfaces: ['fabric', 'grey', 'blue', 'green', 'linen', 'rust', 'white'],
    stands: 'free',
    symbol: 'gym-bench.svg',
    rooms: ['home_gym'],
  },
  {
    id: 'yoga-mat',
    label: 'Yoga Mat',
    size: { width: 610, depth: 1727 },
    surfaces: ['white', 'grey', 'black'],
    stands: 'free',
    layer: 'under',
    symbol: 'yoga-mat.svg',
    rooms: ['home_gym'],
  },
] as const

export const CATALOG_FLOOR_MATERIALS = [
  {
    id: 'brick-beige',
    label: 'Beige brick, stack bond',
    unit: { width: 900, depth: 858 },
    texture: 'surfaces/brick-beige.jpg',
    colour: '#c4b5aa',
  },
  {
    id: 'tile-blue',
    label: 'Blue Square Tile',
    unit: { width: 1600, depth: 1600 },
    texture: 'surfaces/tile-blue.jpg',
    colour: '#bed1e4',
  },
  {
    id: 'ash',
    label: 'Ash',
    unit: { width: 1600, depth: 1350 },
    texture: 'surfaces/ash.jpg',
    colour: '#dfbd96',
  },
  {
    id: 'birch',
    label: 'Birch',
    unit: { width: 1600, depth: 1358 },
    texture: 'surfaces/birch.jpg',
    colour: '#e0d0b7',
  },
  {
    id: 'red-oak',
    label: 'Red Oak',
    unit: { width: 1600, depth: 1350 },
    texture: 'surfaces/red-oak.jpg',
    colour: '#d2a371',
  },
  {
    id: 'tile-hex-mint',
    label: 'Mint Hexagonal Tile',
    unit: { width: 1600, depth: 1386 },
    texture: 'surfaces/tile-hex-mint.jpg',
    colour: '#ebeee7',
  },
  {
    id: 'tile-herringbone',
    label: 'White herringbone tile',
    unit: { width: 1600, depth: 1573 },
    texture: 'surfaces/tile-herringbone.jpg',
    colour: '#f5f2eb',
  },
  {
    id: 'beech',
    label: 'Beech',
    unit: { width: 1600, depth: 1358 },
    texture: 'surfaces/beech.jpg',
    colour: '#d1b088',
  },
  {
    id: 'tile-beige',
    label: 'Beige Square Tile',
    unit: { width: 1024, depth: 1024 },
    texture: 'surfaces/tile-beige.jpg',
    colour: '#edebe6',
  },
  {
    id: 'concrete-light',
    label: 'Concrete - Light',
    unit: { width: 1600, depth: 1147 },
    texture: 'surfaces/concrete-light.jpg',
    colour: '#dbdad6',
  },
  {
    id: 'tile-slate',
    label: 'Slate grey tile, half bond',
    unit: { width: 759, depth: 790 },
    texture: 'surfaces/tile-slate.jpg',
    colour: '#a1aba4',
  },
  {
    id: 'marble-beige',
    label: 'Beige Marble',
    unit: { width: 724, depth: 692 },
    texture: 'surfaces/marble-beige.jpg',
    colour: '#e7dac9',
  },
  {
    id: 'brick-red',
    label: 'Red brick, half bond',
    unit: { width: 900, depth: 799 },
    texture: 'surfaces/brick-red.jpg',
    colour: '#ac7f69',
  },
  {
    id: 'tile-white',
    label: 'White Square Tile',
    unit: { width: 1024, depth: 1024 },
    texture: 'surfaces/tile-white.jpg',
    colour: '#efefed',
  },
  {
    id: 'brick-grey',
    label: 'Grey brick, half bond',
    unit: { width: 900, depth: 879 },
    texture: 'surfaces/brick-grey.jpg',
    colour: '#a39b95',
  },
  {
    id: 'white-oak',
    label: 'White Oak',
    unit: { width: 1600, depth: 1358 },
    texture: 'surfaces/white-oak.jpg',
    colour: '#e8dac6',
  },
  {
    id: 'tile-seafoam',
    label: 'Seafoam Square Tile',
    unit: { width: 1024, depth: 1024 },
    texture: 'surfaces/tile-seafoam.jpg',
    colour: '#a8b5b3',
  },
  {
    id: 'calacatta',
    label: 'Calacatta Gold',
    unit: { width: 1600, depth: 1066 },
    texture: 'surfaces/calacatta.jpg',
    colour: '#f0eeed',
  },
  {
    id: 'tile-terracotta',
    label: 'Terracotta scale tile',
    unit: { width: 1600, depth: 1600 },
    texture: 'surfaces/tile-terracotta.jpg',
    colour: '#deb69b',
  },
  {
    id: 'natural-oak',
    label: 'Natural Oak',
    unit: { width: 1600, depth: 1350 },
    texture: 'surfaces/natural-oak.jpg',
    colour: '#d0a87f',
  },
  {
    id: 'concrete-dark',
    label: 'Concrete - Dark',
    unit: { width: 1000, depth: 1000 },
    texture: 'surfaces/concrete-dark.jpg',
    colour: '#bdbdbd',
  },
  {
    id: 'marble-white',
    label: 'Marble',
    unit: { width: 1024, depth: 1024 },
    texture: 'surfaces/marble-white.jpg',
    colour: '#fafafa',
  },
  {
    id: 'limestone',
    label: 'Limestone',
    unit: { width: 1560, depth: 1600 },
    texture: 'surfaces/limestone.jpg',
    colour: '#eae3dc',
  },
  {
    id: 'granite',
    label: 'Granite',
    unit: { width: 1024, depth: 1024 },
    texture: 'surfaces/granite.jpg',
    colour: '#a1a09c',
  },
  {
    id: 'terrazzo-stone',
    label: 'Terrazzo',
    unit: { width: 1600, depth: 1600 },
    texture: 'surfaces/terrazzo-stone.jpg',
    colour: '#e1e0df',
  },
  {
    id: 'soapstone',
    label: 'Soapstone',
    unit: { width: 1024, depth: 1024 },
    texture: 'surfaces/soapstone.jpg',
    colour: '#656360',
  },
] as const

export const CATALOG_FINISHES = [
  { id: 'white', label: 'White', category: 'paint', colour: '#ffffff' },
  { id: 'black', label: 'Black', category: 'paint', colour: '#000000' },
  {
    id: 'brick-beige',
    label: 'Beige brick, stack bond',
    category: 'brick',
    picture: 'finishes/brick-beige.jpg',
  },
  { id: 'oak-dark', label: 'Oak - Dark', category: 'wood', picture: 'finishes/oak-dark.jpg' },
  {
    id: 'metal-steel',
    label: 'Stainless steel',
    category: 'metal',
    picture: 'finishes/metal-steel.jpg',
  },
  {
    id: 'tile-blue',
    label: 'Blue Square Tile',
    category: 'tile',
    picture: 'finishes/tile-blue.jpg',
  },
  { id: 'ash-light', label: 'Ash - Light', category: 'wood', picture: 'finishes/ash-light.jpg' },
  {
    id: 'ash-natural',
    label: 'Ash - Natural',
    category: 'wood',
    picture: 'finishes/ash-natural.jpg',
  },
  {
    id: 'tile-hex-mint',
    label: 'Mint Hexagonal Tile',
    category: 'tile',
    picture: 'finishes/tile-hex-mint.jpg',
  },
  {
    id: 'tile-herringbone',
    label: 'White herringbone tile',
    category: 'tile',
    picture: 'finishes/tile-herringbone.jpg',
  },
  {
    id: 'oak-paneling',
    label: 'Oak Paneling',
    category: 'wood_paneling',
    picture: 'finishes/oak-paneling.jpg',
  },
  {
    id: 'tile-beige',
    label: 'Beige Square Tile',
    category: 'tile',
    picture: 'finishes/tile-beige.jpg',
  },
  {
    id: 'concrete-light',
    label: 'Concrete - Light',
    category: 'concrete',
    picture: 'finishes/concrete-light.jpg',
  },
  {
    id: 'tile-slate',
    label: 'Slate grey tile, half bond',
    category: 'tile',
    picture: 'finishes/tile-slate.jpg',
  },
  {
    id: 'white-wood-paneling',
    label: 'White Wood Paneling',
    category: 'wood_paneling',
    picture: 'finishes/white-wood-paneling.jpg',
  },
  {
    id: 'marble-beige',
    label: 'Beige Marble',
    category: 'stone',
    picture: 'finishes/marble-beige.jpg',
  },
  {
    id: 'brick-red',
    label: 'Red brick, half bond',
    category: 'brick',
    picture: 'finishes/brick-red.jpg',
  },
  {
    id: 'tile-white',
    label: 'White Square Tile',
    category: 'tile',
    picture: 'finishes/tile-white.jpg',
  },
  {
    id: 'brick-grey',
    label: 'Grey brick, half bond',
    category: 'brick',
    picture: 'finishes/brick-grey.jpg',
  },
  {
    id: 'metal-zinc',
    label: 'Metal - Zinc',
    category: 'metal',
    picture: 'finishes/metal-zinc.jpg',
  },
  {
    id: 'tile-seafoam',
    label: 'Seafoam Square Tile',
    category: 'tile',
    picture: 'finishes/tile-seafoam.jpg',
  },
  {
    id: 'metal-bronze',
    label: 'Metal - Bronze',
    category: 'metal',
    picture: 'finishes/metal-bronze.jpg',
  },
  {
    id: 'metal-gold',
    label: 'Metal - Gold',
    category: 'metal',
    picture: 'finishes/metal-gold.jpg',
  },
  { id: 'acorn', label: 'Acorn', category: 'wood', picture: 'finishes/acorn.jpg' },
  { id: 'oak-medium', label: 'Oak - Medium', category: 'wood', picture: 'finishes/oak-medium.jpg' },
  {
    id: 'calacatta',
    label: 'Calacatta Gold',
    category: 'stone',
    picture: 'finishes/calacatta.jpg',
  },
  {
    id: 'tile-terracotta',
    label: 'Terracotta scale tile',
    category: 'tile',
    picture: 'finishes/tile-terracotta.jpg',
  },
  {
    id: 'concrete-dark',
    label: 'Concrete - Dark',
    category: 'concrete',
    picture: 'finishes/concrete-dark.jpg',
  },
  { id: 'marble-white', label: 'Marble', category: 'stone', picture: 'finishes/marble-white.jpg' },
  { id: 'limestone', label: 'Limestone', category: 'stone', picture: 'finishes/limestone.jpg' },
  { id: 'granite', label: 'Granite', category: 'stone', picture: 'finishes/granite.jpg' },
  { id: 'walnut', label: 'Walnut', category: 'wood', picture: 'finishes/walnut.jpg' },
  { id: 'oak-light', label: 'Oak - Light', category: 'wood', picture: 'finishes/oak-light.jpg' },
  { id: 'maple', label: 'Maple', category: 'wood', picture: 'finishes/maple.jpg' },
  { id: 'cherry', label: 'Cherry', category: 'wood', picture: 'finishes/cherry.jpg' },
  { id: 'terrazzo', label: 'Terrazzo', category: 'concrete', picture: 'finishes/terrazzo.jpg' },
  { id: 'soapstone', label: 'Soapstone', category: 'stone', picture: 'finishes/soapstone.jpg' },
] as const

export const CATALOG_STYLES = [
  {
    id: 'scandinavian',
    label: 'Scandinavian',
    blurb: 'pale timber, white walls and plenty of daylight, kept plain and calm',
    picture: 'finishes/styles/scandinavian.jpg',
    defaults: {
      ceiling: 'white',
      floor: 'white-oak',
      bathroomFloor: 'tile-white',
      walls: 'white',
      doors: 'white',
      windows: 'white',
    },
  },
  {
    id: 'coastal',
    label: 'Coastal',
    blurb:
      'sun-bleached boards, white panelling and the soft colours of sand and sea',
    picture: 'finishes/styles/coastal.jpg',
    defaults: {
      floor: 'birch',
      bathroomFloor: 'tile-herringbone',
      walls: 'white-wood-paneling',
      doors: 'white',
      windows: 'white',
      ceiling: 'white',
    },
  },
  {
    id: 'farmhouse',
    label: 'Farmhouse',
    blurb:
      'white boarded walls, honest timber and a homely, lived-in warmth',
    picture: 'finishes/styles/farmhouse.jpg',
    defaults: {
      walls: 'white-wood-paneling',
      doors: 'white',
      windows: 'oak-medium',
      ceiling: 'white',
      floor: 'ash',
      bathroomFloor: 'tile-white',
    },
  },
  {
    id: 'industrial',
    label: 'Industrial',
    blurb: 'bare concrete, black steel and the hard edges of a converted workshop',
    picture: 'finishes/styles/industrial.jpg',
    defaults: {
      ceiling: 'concrete-light',
      floor: 'concrete-light',
      bathroomFloor: 'tile-beige',
      walls: 'concrete-light',
      doors: 'white',
      windows: 'black',
    },
  },
  {
    id: 'midcentury-modern',
    label: 'Midcentury Modern',
    blurb: 'walnut and slate, low clean lines and a few confident colours',
    picture: 'finishes/styles/midcentury-modern.jpg',
    defaults: {
      floor: 'tile-slate',
      bathroomFloor: 'tile-beige',
      walls: 'white',
      doors: 'white',
      windows: 'walnut',
      ceiling: 'oak-paneling',
    },
  },
  {
    id: 'traditional',
    label: 'Traditional',
    blurb:
      'beech underfoot, white joinery and calm, balanced proportions',
    picture: 'finishes/styles/traditional.jpg',
    defaults: {
      bathroomFloor: 'tile-beige',
      walls: 'white',
      doors: 'white',
      windows: 'white',
      ceiling: 'white',
      floor: 'beech',
    },
  },
  {
    id: 'rustic',
    label: 'Rustic',
    blurb: 'oak on floor, walls and ceiling, rough and warm like a mountain cabin',
    picture: 'finishes/styles/rustic.jpg',
    defaults: {
      floor: 'natural-oak',
      bathroomFloor: 'tile-beige',
      walls: 'oak-paneling',
      doors: 'white',
      windows: 'oak-medium',
      ceiling: 'oak-paneling',
    },
  },
  {
    id: 'modern',
    label: 'Modern',
    blurb:
      'white surfaces, black-framed glazing and nothing that is not needed',
    picture: 'finishes/styles/modern.jpg',
    defaults: {
      floor: 'white-oak',
      bathroomFloor: 'tile-herringbone',
      walls: 'white',
      doors: 'white',
      windows: 'black',
      ceiling: 'white',
    },
  },
] as const
